name: routine-qc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - fastqc=0.11.9
  - multiqc=1.9
  - illumina-interop=1.1.21
  - sample-sheet=0.12.0
  - kraken2=2.1.1
  - bracken=2.6.0
  - mash=2.3
