name: Build Container Images

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - name: Install Wave CLI
        run: |
          .github/scripts/install_wave-cli.sh
      - name: Check wave installation
        run: wave --version
      - name: Build images
        run: |
          .github/scripts/build_container_images.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: artifacts-BCCDC-PHL-routine-sequence-qc-build-containers-${{ github.run_id }}.${{ github.run_attempt }}
          path: artifacts
